spring:
  application:
    name: emotionalConnectionApp

  datasource:
    url: jdbc:postgresql://localhost:5432/closerdb
    username: closer
    password: closer
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080
